[Alignment 2.0] use Versions and filter/sort versions by Ranking system
project-ncl/dependency-analysis pull request #561
Opened 2023-04-25 15:12 UTC by michalovjan

### Checklist:

* [ ] Have you added a note in the [Changelog](https://github.com/project-ncl/dependency-analysis/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

Dependencies:
requires https://github.com/project-ncl/pnc-api/pull/141
requires https://github.com/project-ncl/pnc-common/pull/46
requires https://github.com/project-ncl/pnc/pull/3697

### Notable changes:
#### Introduction of **QualifiedVersion** in DA:

In order for DA to consume artifacts' versions enhanced with Qualifier data, I had to refactor a sizable portion of DA starting from data-layer where DA retrieves versions of products from PNC and/or Indy and bubble it up to a layer where DA processes and analyses Versions. 

I've put a strong emphasis on backward compatibility inside the code itself so that anything that worked with simple version strings would not be affected at all apart from occasional mapping QualifiedVersion<->String.

Additionally, in case we ever want to use manipulation on NPM artifacts, I've tried to make the code generic so that everything would be reusable/copy-worthy for the future. 

#### New field for **MavenLookupRequest** which is used by **GME/PME for alignment manipulation**:

The new field **Set\<Strategy\>** consists of 4 fields:
1. _artifactScope_:
   - If it's null, strategies are applied on all GAV in LookupRequests. Otherwise, it can specify G, GA or GAV as scope to which GAVs apply the strategies. More specific scopes override less specific ones.
2. _ranks_:
   - Defines preferences of user which artifacts to prefer. Consists of ranks of Qualifiers which are PNC-specific data.
3. _denyList_
   - Comma-seperated list of Qualifiers which should be excluded from analyses. 
5. _allowList_
   - Comma-seperated list of Qualifiers which should be exclusively included in analysis. 

Allow-list is evaluated before deny-list. 

#### VersionAnalyzer changes:

Uses _ranks_, _allowList_ and _denyList_ to analyze versions. These are currently used just for findBiggestMatchingVersion() method as that was the scope of alignment manipulation. If there would be desire to add the ranking/filtering functionality to other parts of VersionAnalyzer, it should be possible. 

The default behaviour remains the same as before, without any ranks and allow/denyLists. They are still applied but their default behaviour is the same. 

The algorithm used in the findBiggestMatchingVersion() to get 'highest build number' was extracted into a form that would comply with `Compataror<String>`. That Comparator is loaded into a Ranking `overrideVersionComparator(this::compareByBuildNumber)`. That comparator is used everytime because a rank that sorts _QualifiedVersions by version string_ is mandatory and it is always the last rank ("SUFFIX-VERSION"). This enables DA to choose how to compare version strings in case there is more than one algorithm it wants to use.

2023-05-04 11:40 UTC, michalovjan commented
Renamed Version model into QualifiedVersion, merged in https://github.com/project-ncl/pnc-api/pull/144

2023-05-04 15:21 UTC, janinko requested changes

2023-05-04 15:21 UTC, janinko commented on reports-backend/src/main/java/org/jboss/da/reports/impl/LookupGeneratorImpl.java
> +        return strategies == null ? Set.of()
Use if, it's more readable

2023-05-04 15:32 UTC, michalovjan commented on communication/src/main/java/org/jboss/da/communication/pnc/PncConnectorImpl.java
> +                log.error("Cannot read version for artifact with identifier {}", art.getIdentifier());
good question

2023-05-04 15:36 UTC, michalovjan commented on reports-backend/src/main/java/org/jboss/da/reports/impl/LookupGeneratorImpl.java
> +            return vas.get(max.get());
++

2023-05-04 20:07 UTC, michalovjan commented on common/src/test/java/org/jboss/da/common/version/VersionAnalyzerTest.java
> +import org.jboss.pnc.api.dependencyanalyzer.dto.QualifiedVersion;
For sure, if only we had a better formatter that wouldn't make the tests less readable...

2023-05-05 14:09 UTC, janinko commented on reports-model/src/main/java/org/jboss/da/model/rest/Strategy.java
> +@EqualsAndHashCode
if the fields are final, they don't have setters. But `@Value` is also fine

2023-05-05 14:19 UTC, janinko approved these changes

2023-05-05 20:21 UTC, michalovjan commented
retest this please

2023-05-05 20:58 UTC, merged